# Generated by Django 4.0.4 on 2022-06-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_notificarme_contacto_is_notificarme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='is_Notificarme',
            new_name='Notificarme',
        ),
    ]
